version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PORT=${PORT}  
      - DATABASE_URL=${DATABASE_URL_PROD}
    restart: always
    command: >
      /bin/sh -c "wait-for-it db:5432 --  
      && npx prisma generate 
      && npx prisma migrate dev --name init 
      && npm start"

  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: megaJunior
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jubileutaskapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
