name: Test PRs

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install, build and test
        run: |
          npm install --legacy-peer-deps
          npm run build
          npm test
