name: Test PRs

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x 

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set DATABASE_URL for SQLite
        run: echo "DATABASE_URL=sqlite:./prisma/dev.db" >> $GITHUB_ENV  # Aqui define o SQLite como o banco de dados

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run migrations
        run: npx prisma migrate deploy --schema=./prisma/schema.dev.prisma  # Usando o arquivo de esquema correto

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test
